name: Deploy Workflow
on: [push, workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: Downloader
            uses: robinraju/release-downloader@v1
            with:
                repository: 'bepass-org/oblivion-desktop'
                latest: true
                fileName: '*'
                out-file-path: 'downloaded'
defaults:
 run:
  working-directory: /assets/
