name: Deploy Workflow
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      -   name: Downloader
          uses: robinraju/release-downloader@v1
          with:
                repository: 'bepass-org/oblivion-desktop'
                latest: true
                fileName: '*'
                out-file-path: 'downloaded'
      -  name: send created sub
         uses: appleboy/telegram-action@master
         with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: سرورهای رایگان جمع آوری شده
          document: /home/runner/work/autorelease_uploader/autorelease_uploader/downloaded/oblivion-desktop-linux-aarch64.rpm,/home/runner/work/autorelease_uploader/autorelease_uploader/downloaded/oblivion-desktop-linux-amd64.deb
