name: Deploy Workflow
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      -   name: Downloader
          uses: robinraju/release-downloader@v1
          with:
                repository: 'bepass-org/oblivion-desktop'
                latest: true
                fileName: '*'
                out-file-path: 'downloaded'
      -   name: Upload logs
          uses: actions/upload-artifact@v2
          with:
            name: retrieve
            path: /home/runner/work/autorelease_uploader/autorelease_uploader/downloaded/*
            retention-days: 5
